const mongoose = require('mongoose');

const reviewSchema = new mongoose.Schema({
    prId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'PullRequest',
        required: true,
    },
    // Individual review comments generated by GPT-4o-mini
    comments: [
        {
            file: { type: String, required: true },       // File path in the repo
            line: { type: Number, required: true },        // Line number
            issue: { type: String, required: true },       // What the AI found
            suggestion: { type: String, default: '' },     // Suggested fix
            type: {
                type: String,
                enum: ['bug', 'style', 'performance', 'security', 'suggestion'],
                default: 'suggestion',
            },
        },
    ],
    // Plain English overview of the entire PR
    summary: {
        type: String,
        default: '',
    },
    createdAt: {
        type: Date,
        default: Date.now,
    },
});

module.exports = mongoose.model('Review', reviewSchema);
